### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lomorster** [MorsGames/sm64plus#76]
**FIXED IT PLEASE DELETE OR CLOSE ISSUE**
**FIXED IT PLEASE DELETE OR CLOSE ISSUE**
**FIXED IT PLEASE DELETE OR CLOSE ISSUE**
**FIXED IT PLEASE DELETE OR CLOSE ISSUE**
**FIXED IT PLEASE DELETE OR CLOSE ISSUE**
When i give it a rom it gives me this error any solution?
I followed the guide

==== Build Options ====
Version:        us
Microcode:      f3dex2e
Target:         sm64.us
Compare ROM:    no
Build Matching: no
=======================
make: gcc: No such file or directory
make: *** [Makefile:78: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/USER/sm64plus/extract_assets.py", line 292, in <module>
    main()
  File "/home/USER/sm64plus/extract_assets.py", line 166, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:222: *** Failed to extract assets.  Stop.

**Comment by lomorster** [comment]
I used UCRT64 instead of MINGW64......
I am on windows btw
